-- Dashboard Portal - versión estática para GitHub Pages
-- Ejecutar en Supabase SQL Editor.
-- Esta migración permite que la SPA estática consulte Supabase directamente con RLS.
-- No requiere service_role en el navegador y no almacena secretos.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  role text not null default 'user' check (role in ('admin', 'user')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.dashboards (
  id text primary key,
  name text not null,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.dashboard_access (
  user_id uuid not null references public.profiles(id) on delete cascade,
  dashboard_id text not null references public.dashboards(id) on delete cascade,
  permission text not null check (permission in ('read', 'write')),
  created_at timestamptz not null default now(),
  primary key (user_id, dashboard_id)
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text,
  action text not null,
  dashboard_id text references public.dashboards(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.dashboards (id, name, description, active)
values
  ('ventas', 'Ventas', 'Indicadores comerciales, ingresos y conversión.', true),
  ('inventarios', 'Inventarios', 'Stock, rotación y alertas de disponibilidad.', true),
  ('produccion', 'Producción', 'Órdenes, cumplimiento operativo e incidencias.', true)
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  active = excluded.active;

create index if not exists idx_audit_log_created_at on public.audit_log (created_at desc);
create index if not exists idx_audit_log_actor_id on public.audit_log (actor_id);
create index if not exists idx_audit_log_dashboard_id on public.audit_log (dashboard_id);
create index if not exists idx_dashboard_access_user_id on public.dashboard_access (user_id);
create index if not exists idx_dashboard_access_dashboard_id on public.dashboard_access (dashboard_id);

alter table public.profiles enable row level security;
alter table public.dashboards enable row level security;
alter table public.dashboard_access enable row level security;
alter table public.audit_log enable row level security;

-- Funciones SECURITY DEFINER para evitar recursión en policies sobre profiles.
create or replace function public.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.active = true
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.active = true
      and p.role = 'admin'
  );
$$;

grant execute on function public.is_active_user() to authenticated;
grant execute on function public.is_admin() to authenticated;

-- Trigger para crear profile cuando se crea un usuario en Supabase Auth.
create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role, active)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'name', new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, ''), '@', 1), ''),
    'user',
    true
  )
  on conflict (id) do update
  set
    email = excluded.email,
    name = case
      when public.profiles.name is null or public.profiles.name = '' then excluded.name
      else public.profiles.name
    end;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute function public.handle_new_user_profile();

-- Importa usuarios que ya existían antes de ejecutar la migración.
insert into public.profiles (id, email, name, role, active, created_at)
select
  u.id,
  coalesce(u.email, ''),
  coalesce(u.raw_user_meta_data ->> 'name', u.raw_user_meta_data ->> 'full_name', split_part(coalesce(u.email, ''), '@', 1), ''),
  'user',
  true,
  coalesce(u.created_at, now())
from auth.users u
on conflict (id) do nothing;

-- Limpieza de policies previas si se re-ejecuta esta migración.
drop policy if exists profiles_select_self_or_admin on public.profiles;
drop policy if exists profiles_update_admin_not_self on public.profiles;
drop policy if exists dashboards_select_active_users on public.dashboards;
drop policy if exists dashboards_write_admin on public.dashboards;
drop policy if exists dashboard_access_select_self_or_admin on public.dashboard_access;
drop policy if exists dashboard_access_insert_admin on public.dashboard_access;
drop policy if exists dashboard_access_update_admin on public.dashboard_access;
drop policy if exists dashboard_access_delete_admin on public.dashboard_access;
drop policy if exists audit_log_insert_self on public.audit_log;
drop policy if exists audit_log_select_admin on public.audit_log;

-- PROFILES
-- Cada usuario activo puede leer su propio perfil; admin puede leer usuarios.
create policy profiles_select_self_or_admin
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_admin());

-- Admin puede activar/desactivar y editar perfiles de otros usuarios.
-- Se impide la edición de su propia fila para reducir riesgo de autodesactivación accidental.
create policy profiles_update_admin_not_self
on public.profiles
for update
to authenticated
using (public.is_admin() and id <> auth.uid())
with check (public.is_admin());

-- DASHBOARDS
create policy dashboards_select_active_users
on public.dashboards
for select
to authenticated
using ((active = true and public.is_active_user()) or public.is_admin());

create policy dashboards_write_admin
on public.dashboards
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- DASHBOARD ACCESS
create policy dashboard_access_select_self_or_admin
on public.dashboard_access
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy dashboard_access_insert_admin
on public.dashboard_access
for insert
to authenticated
with check (public.is_admin());

create policy dashboard_access_update_admin
on public.dashboard_access
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy dashboard_access_delete_admin
on public.dashboard_access
for delete
to authenticated
using (public.is_admin());

-- AUDITORÍA
-- Usuarios activos insertan solo eventos propios. Admin lee todos los eventos.
create policy audit_log_insert_self
on public.audit_log
for insert
to authenticated
with check (actor_id = auth.uid() and public.is_active_user());

create policy audit_log_select_admin
on public.audit_log
for select
to authenticated
using (public.is_admin());

-- Revoca acceso directo anónimo.
revoke all on public.profiles from anon;
revoke all on public.dashboard_access from anon;
revoke all on public.audit_log from anon;
revoke all on public.dashboards from anon;

-- Concede acceso al rol authenticated; RLS decide fila por fila.
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.dashboards to authenticated;
grant select, insert, update, delete on public.dashboard_access to authenticated;
grant select, insert on public.audit_log to authenticated;
grant usage, select on sequence public.audit_log_id_seq to authenticated;
