-- Dashboard Portal - esquema inicial
-- Las tablas sensibles usan RLS sin policies para anon/authenticated.
-- El backend de Next.js accede con SUPABASE_SECRET_KEY y valida el JWT del usuario.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  role text not null default 'user' check (role in ('admin', 'user')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_email_lower_idx
  on public.profiles (lower(email));

create table if not exists public.dashboards (
  id text primary key,
  name text not null,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.dashboard_access (
  user_id uuid not null references public.profiles(id) on delete cascade,
  dashboard_id text not null references public.dashboards(id) on delete cascade,
  permission text not null check (permission in ('read', 'write')),
  created_at timestamptz not null default now(),
  primary key (user_id, dashboard_id)
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text not null,
  action text not null,
  dashboard_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_log_created_at_idx
  on public.audit_log (created_at desc);

create index if not exists audit_log_actor_id_idx
  on public.audit_log (actor_id);

create index if not exists audit_log_dashboard_id_idx
  on public.audit_log (dashboard_id);

create index if not exists dashboard_access_dashboard_id_idx
  on public.dashboard_access (dashboard_id);

insert into public.dashboards (id, name, description, active)
values
  ('ventas', 'Ventas', 'Indicadores comerciales y seguimiento de ventas.', true),
  ('inventarios', 'Inventarios', 'Existencias, movimientos y control de inventario.', true),
  ('produccion', 'Producción', 'Seguimiento operativo y métricas de producción.', true)
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role, active, created_at)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'name', ''), split_part(coalesce(new.email, ''), '@', 1), 'Usuario'),
    'user',
    true,
    coalesce(new.created_at, now())
  )
  on conflict (id) do update
  set
    email = excluded.email,
    name = case
      when public.profiles.name = '' then excluded.name
      else public.profiles.name
    end;

  return new;
end;
$$;

-- Importa usuarios existentes sin otorgar privilegios administrativos automáticamente.
insert into public.profiles (id, email, name, role, active, created_at)
select
  u.id,
  coalesce(u.email, ''),
  coalesce(nullif(u.raw_user_meta_data ->> 'name', ''), split_part(coalesce(u.email, ''), '@', 1), 'Usuario'),
  'user',
  true,
  coalesce(u.created_at, now())
from auth.users u
on conflict (id) do nothing;

drop trigger if exists on_auth_user_created_dashboard_portal on auth.users;

create trigger on_auth_user_created_dashboard_portal
after insert on auth.users
for each row execute function public.handle_new_auth_user();

alter table public.profiles enable row level security;
alter table public.dashboards enable row level security;
alter table public.dashboard_access enable row level security;
alter table public.audit_log enable row level security;

-- Defensa en profundidad: el navegador (anon/authenticated) no accede directamente.
-- No se crean policies de lectura/escritura para estas tablas.
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.dashboards from anon, authenticated;
revoke all on table public.dashboard_access from anon, authenticated;
revoke all on table public.audit_log from anon, authenticated;

-- El backend utiliza la clave privada de Supabase, que representa el rol service_role.
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.profiles to service_role;
grant select, insert, update, delete on table public.dashboards to service_role;
grant select, insert, update, delete on table public.dashboard_access to service_role;
grant select, insert, update, delete on table public.audit_log to service_role;
grant usage, select on all sequences in schema public to service_role;
